services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - mongo
    environment:
      - DJANGO_SETTINGS_MODULE=myproject.settings
    restart: always

  mongo:
    image: mongo:6
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
