services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:6
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A zibal worker --loglevel=info
    depends_on:
      - redis
      - web

  celery-beat:
    build: .
    command: celery -A zibal beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - redis
      - web


volumes:
  mongo_data:
